# Generated by Django 5.1.4 on 2025-04-27 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Pens', 'Pens'), ('Pencils', 'Pencils'), ('Notebooks', 'Notebooks'), ('Erasers', 'Erasers'), ('Others', 'Others')], default='Others', max_length=50),
        ),
    ]
